export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_FAILURE = "ADD_TO_WISHLIST_FAILURE";

export const GET_WISHLIST_ITEMS_REQUEST = "GET_WISHLIST_ITEMS_REQUEST";
export const GET_WISHLIST_ITEMS_SUCCESS = "GET_WISHLIST_ITEMS_SUCCESS";
export const GET_WISHLIST_ITEMS_FAILURE = "GET_WISHLIST_ITEMS_FAILURE";

export const REMOVE_WISHLIST_ITEM_REQUEST = "REMOVE_WISHLIST_ITEM_REQUEST";
export const REMOVE_WISHLIST_ITEM_SUCCESS = "REMOVE_WISHLIST_ITEM_SUCCESS";
export const REMOVE_WISHLIST_ITEM_FAILURE = "REMOVE_WISHLIST_ITEM_FAILURE";

export const CLEAR_WISHLIST_ITEMS = "CLEAR_WISHLIST_ITEMS";