export const TOGGLE_SHOPPING_CART = "TOGGLE_SHOPPING_CART";
export const SHOW_SHOPPING_CART = "SHOW_SHOPPING_CART";
export const HIDE_SHOPPING_CART = "HIDE_SHOPPING_CART";
export const TRIGGER_ADD_TO_CART = "TRIGGER_ADD_TO_CART";
export const DESTROYED_TRIGGERED_FLAG = "DESTROYED_TRIGGERED_FLAG";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const GET_CART_ITEMS_REQUEST = "GET_CART_ITEMS_REQUEST";
export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS";
export const GET_CART_ITEMS_FAILURE = "GET_CART_ITEMS_FAILURE";

export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_FAILURE = "REMOVE_CART_ITEM_FAILURE";

export const CHECK_UNCHECK_CART_ITEM_REQUEST =
  "CHECK_UNCHECK_CART_ITEM_REQUEST";
export const CHECK_UNCHECK_CART_ITEM_SUCCESS =
  "CHECK_UNCHECK_CART_ITEM_SUCCESS";
export const CHECK_UNCHECK_CART_ITEM_FAILURE =
  "CHECK_UNCHECK_CART_ITEM_FAILURE";

export const GET_SKU_LIST_REQUEST = "GET_SKU_LIST_REQUEST";
export const GET_SKU_LIST_SUCCESS = "GET_SKU_LIST_SUCCESS";
export const GET_SKU_LIST_FAILURE = "GET_SKU_LIST_FAILURE";

export const CLEAR_CART = "CLEAR_CART";
